version: '3'


services:
  acme: # name of service
    container_name: acme-container 
    build: . # build from Dockerfile in current directory
    ports:
      - "${NODE_PORT:-8080}:8080"
    restart: on-failure # restart if service fails
    depends_on:
      - mongodb # wait for mongodb to be ready
    
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      
  mongodb: # name of service
    image: "mongo" # pull from Docker Hub
    command: --logpath /var/log/mongodb/db.log
    ports:
      - "${MONGO_PORT:-27015}:27017"
    volumes:
      - "datavol:/data/db" # mount local directory to container directory
      - "logging-db-acme:/var/log/mongodb" # mount local directory to container directory
      
volumes:
  logging-acme:
    external: true #esto quiere decir que docker compose no lo va a crear, sino que lo va a buscar en el host
  datavol:
  logging-db-acme:
    external: true